### PR TITLE
Gjs fix

### LINKED ISSUE #35: Not compatible with gjs >= 1.53.90
Trying to launch the extension preferences dialog gives the following:

```
SyntaxError: missing ( after for

Stack trace:
  _getExtensionPrefsModule@resource:///org/gnome/shell/extensionPrefs/main.js:76:13
  wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
  _selectExtension@resource:///org/gnome/shell/extensionPrefs/main.js:91:31
  wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
  _onCommandLine@resource:///org/gnome/shell/extensionPrefs/main.js:244:17
  wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
  main@resource:///org/gnome/shell/extensionPrefs/main.js:398:5
  @<main>:1:43
  ```

### PR DESCRIPTION
**Pull request by theychx**
fixes #35

@brunelli Can you give this a spin, just to be on the safe side?

### CODE REVIEW

**Comment by brunelli** [comment]
Why is gnome-shell < 3.30 support being dropped? I think it should still work with gjs < 1.53.90, no?

As for the changes in fb46f029b98ea536f8c0814c627ca5a30c42dbc7, it works as expected in gnome-shell 3.30 + gjs 1.54.1!

**Comment by theychx** [comment]
> I think it should still work with gjs < 1.53.90, no?

I'm not much of an gjs/js expert, honestly, so I am not going to assume this (unless you are 100% sure). And besides, the old version will still be available from extensions.gnome.org to <3.30 users.

**Comment by theychx** [comment]
It works with ```1.52.3``` obviously, but I have no way of knowing with older versions.

**Comment by brunelli** [comment]
> It works with 1.52.3

Then we are fine. The related change was introduced with gjs upgrading SpiderMonkey to version 60. The last SpiderMonkey upgrade before that was with gjs 1.49.4, [released in July/17](https://gitlab.gnome.org/GNOME/gjs/commit/dca17105ebedaa1c04befa4db4a073245af00ae9).

> the old version will still be available from extensions.gnome.org to <3.30 users

But it will keep them from further updates.

**Comment by theychx** [comment]
@brunelli Thank you for your help!

**Pull request merged**
